#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/sieg/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it
xrandr --output HDMI-1-0 --mode 1920x1080 --right-of eDP-1
nitrogen --restore
.config/polybar/launch.sh --cuts

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/sieg/.fluxbox/log"
